cloud:
  aws:
    credentials:
      accessKey: ${AWS_ACCESS_KEY}
      secretKey: ${AWS_SECRET_KEY}
    s3:
      bucket: greenus
      dir: /greenus
    region:
      static: ap-northeast-2
    stack:
      auto: false
    cloudfront:
      domain: ${AWS_CLOUDFRONT_DOMAIN}