springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  api-docs:
    groups:
      enabled: true
  swagger-ui:
    operations-sorter: alpha # alpha(??? ????), method(HTTP????)
    tags-sorter: alpha # ?? ?? ??
    path: /swagger-ui.html # html ?? ?? ??
    disable-swagger-default-url: true
    display-query-params-without-oauth2: true
    doc-expansion: none # tag, operation ??? ??
  paths-to-match:
    - /**

oauth:
  google:
    client-id: client-id
    client-secret: client-secret
    oauth-end-point: https://accounts.google.com/o/oauth2/v2/auth
    response-type: code
    scopes:
      - https://www.googleapis.com/auth/userinfo.profile
      - https://www.googleapis.com/auth/userinfo.email
    token-uri: https://oauth2.googleapis.com/token
    access-type: offline